using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.IO;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Gomoku
{
    public class MainForm : Form
    {
        // ── 版面配置常數 ────────────────────────────────────────────
        private const int Cell    = 38;
        private const int Pad     = 33;
        private const int Radius  = 15;
        private const int Grid    = (GomokuGame.BoardSize - 1) * Cell;   // 532
        private const int BoardSz = Grid + Pad * 2;                      // 598
        private const int FormW   = 660;
        private const int TopH    = 76;
        private const int BotH    = 128;
        private const int FormH   = TopH + BoardSz + BotH;               // 802
        private const int BoardX  = (FormW - BoardSz) / 2;               // 31
        private const int CardW   = 158;
        private const int CardH   = 58;

        // ── 遊戲物件 ────────────────────────────────────────────────
        private readonly GomokuGame _game = new GomokuGame();
        private readonly GomokuAI   _ai   = new GomokuAI();
        private bool _aiMode      = true;
        private bool _aiThinking  = false;
        private int  _gameVersion = 0;

        // ── 難度顏色 / 名稱 ─────────────────────────────────────────
        private static readonly Color[] DiffColors =
        {
            Color.FromArgb(46, 125, 50),
            Color.FromArgb(21, 101, 192),
            Color.FromArgb(204, 101,  0),
            Color.FromArgb(136,  14, 79)
        };
        private static readonly string[] DiffLabels = { "簡單", "中等", "困難", "大師" };
        private readonly Button[] _diffBtns = new Button[4];

        // ── UI 控制項 ────────────────────────────────────────────────
        private DoubleBufferedPanel _board;
        private Button _btnMusic;
        private Panel  _leftCard;
        private Panel  _rightCard;
        private Label  _lblTimer;
        private Label  _lblStatus;
        private Label  _lblWName;   // 右卡片名稱（「電腦」或「玩家 2」）

        // ── 計時器 / 懸停 ───────────────────────────────────────────
        private readonly System.Windows.Forms.Timer _clock;
        private int   _elapsed = 0;
        private bool  _started = false;
        private Point? _hover  = null;

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // 建構子
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        public MainForm()
        {
            SuspendLayout();

            Text            = "五子棋  Gomoku";
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox     = false;
            BackColor       = Color.FromArgb(24, 24, 32);
            StartPosition   = FormStartPosition.CenterScreen;
            ClientSize      = new Size(FormW, FormH);
            KeyPreview      = true;
            Font            = new Font("Microsoft JhengHei UI", 9f);

            // ── 載入圖示（內嵌 Base64，不需外部檔案） ────────────────
            LoadEmbeddedIcon();

            // 頂部資訊列
            Panel topPanel = new Panel();
            topPanel.Location  = Point.Empty;
            topPanel.Size      = new Size(FormW, TopH);
            topPanel.BackColor = Color.FromArgb(30, 30, 42);
            Controls.Add(topPanel);
            BuildTopPanel(topPanel);

            // 棋盤（置中）
            _board = new DoubleBufferedPanel();
            _board.Location    = new Point(BoardX, TopH);
            _board.Size        = new Size(BoardSz, BoardSz);
            _board.Cursor      = Cursors.Hand;
            _board.Paint      += Board_Paint;
            _board.MouseMove  += Board_MouseMove;
            _board.MouseClick += Board_MouseClick;
            _board.MouseLeave += (s, e) => { _hover = null; _board.Invalidate(); };
            Controls.Add(_board);

            // 底部控制列
            Panel botPanel = new Panel();
            botPanel.Location  = new Point(0, TopH + BoardSz);
            botPanel.Size      = new Size(FormW, BotH);
            botPanel.BackColor = Color.FromArgb(26, 26, 36);
            Controls.Add(botPanel);
            BuildBottomPanel(botPanel);

            // 遊戲計時器
            _clock = new System.Windows.Forms.Timer();
            _clock.Interval = 1000;
            _clock.Tick += (s, e) => { _elapsed++; RefreshTimer(); };

            ResumeLayout(false);

            // 背景音樂（生成需數百毫秒，在背景執行緒完成後自動就緒）
            MusicPlayer.Start();
        }

        /// <summary>從內嵌 Base64 字串載入圖示，不依賴外部 .ico 檔案。</summary>
        private void LoadEmbeddedIcon()
        {
            try
            {
                byte[] iconBytes = Convert.FromBase64String(IconBase64);
                using (MemoryStream ms = new MemoryStream(iconBytes))
                    this.Icon = new Icon(ms);
            }
            catch { /* 載入失敗時沿用預設圖示 */ }
        }

        // ── 圖示 Base64（原始 .ico 內嵌，無需外部檔案） ──────────────

        // ── 圖示 Base64（原始 .ico 內嵌，無需外部檔案） ──────────────
        private const string IconBase64 =
            "AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2+3+AHGm2gB7rNwAY5zaAFiW" +
            "1wBUktQAVpTSACB40QB2qd0ACA" +
            "gKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "vNfxAGqh3ABuo9sA//9vAGKb2RhYltYsU5LTJFmU0Ak/htIAeKfTAGKd0gAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "hLLgAHGl3QB1p9wRY5/egFqb39RUl97rTJLa40aN1rBLjdI7AGHSAIax0AB2qd8AAFG" +
            "fAL7W/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "ibXhALrN2QJqpOGIZaTm/2im6P9ko+b/WZzi/0uS3P9Aidb" +
            "cQ4rOJkmP1wBIj9cATpHUAGSa0ABel9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////////////4Af//8AH///AAP//wAA//8AAH/+AAB/+AAAf/AAAH/AAAB/AAAAfgAAAH4AAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD/AAAA/8AAA//gAA//+AAf//wAf///Af//////////////////////8=";

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // 頂部面板：先加中央 Label，再加卡片（卡片 z-order 在上）
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        private void BuildTopPanel(Panel top)
        {
            const int cardY  = 9;
            // 中央區域：左卡右緣=170，右卡左緣=490，中央寬=320
            const int cX = 174, cW = 312;

            // ── 先加中央 Label（z-order 較低）──────────────────────
            _lblTimer = new Label();
            _lblTimer.Text      = "00:00";
            _lblTimer.Font      = new Font("Consolas", 20, FontStyle.Bold);
            _lblTimer.ForeColor = Color.White;
            _lblTimer.Location  = new Point(cX, 8);
            _lblTimer.Size      = new Size(cW, 32);
            _lblTimer.TextAlign = ContentAlignment.MiddleCenter;
            _lblTimer.AutoSize  = false;
            top.Controls.Add(_lblTimer);

            _lblStatus = new Label();
            _lblStatus.Text      = "您的回合";
            _lblStatus.Font      = new Font("Microsoft JhengHei", 9f);
            _lblStatus.ForeColor = Color.FromArgb(120, 200, 120);
            _lblStatus.Location  = new Point(cX, 43);
            _lblStatus.Size      = new Size(cW, 22);
            _lblStatus.TextAlign = ContentAlignment.MiddleCenter;
            _lblStatus.AutoSize  = false;
            top.Controls.Add(_lblStatus);

            // ── 再加卡片（z-order 在 Label 之上）─────────────────
            // 左卡（黑棋）
            _leftCard = MakeCard(top, 12, cardY, CardW, CardH,
                                 Color.FromArgb(36, 68, 110));

            // ♟ 圖示
            Label lIcon = MakeLbl(_leftCard, "♟",
                new Font("Segoe UI Symbol", 18), Color.FromArgb(130, 200, 130),
                new Point(4, 3), new Size(32, 52));

            // 玩家名稱
            MakeLbl(_leftCard, "玩家",
                new Font("Microsoft JhengHei", 11, FontStyle.Bold), Color.White,
                new Point(40, 5), new Size(114, 22));

            // 顏色標籤
            MakeLbl(_leftCard, "黑棋",
                new Font("Microsoft JhengHei", 7.5f), Color.FromArgb(180, 180, 210),
                new Point(68, 33), new Size(40, 18));

            // 棋子由 Paint 事件繪製，不用 PictureBox（避免透明背景問題）
            _leftCard.Paint += (s, e) =>
            {
                e.Graphics.SmoothingMode = SmoothingMode.AntiAlias;
                DrawPieceSmall(e.Graphics, 51, 41, Player.Black, 11);
            };

            // 右卡（白棋）
            _rightCard = MakeCard(top, FormW - 12 - CardW, cardY, CardW, CardH,
                                  Color.FromArgb(44, 44, 58));

            // ⚙ 圖示
            MakeLbl(_rightCard, "⚙",
                new Font("Segoe UI Symbol", 18), Color.FromArgb(120, 165, 225),
                new Point(CardW - 38, 3), new Size(34, 52));

            // 電腦名稱（可動態更新）
            _lblWName = new Label();
            _lblWName.Text      = "電腦";
            _lblWName.Font      = new Font("Microsoft JhengHei", 11, FontStyle.Bold);
            _lblWName.ForeColor = Color.White;
            _lblWName.Location  = new Point(8, 5);
            _lblWName.Size      = new Size(114, 22);
            _lblWName.AutoSize  = false;
            _rightCard.Controls.Add(_lblWName);

            // 顏色標籤
            MakeLbl(_rightCard, "白棋",
                new Font("Microsoft JhengHei", 7.5f), Color.FromArgb(180, 180, 210),
                new Point(36, 33), new Size(40, 18));

            // 白棋由 Paint 事件繪製
            _rightCard.Paint += (s, e) =>
            {
                e.Graphics.SmoothingMode = SmoothingMode.AntiAlias;
                DrawPieceSmall(e.Graphics, 22, 41, Player.White, 11);
            };
        }

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // 底部面板
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        private void BuildBottomPanel(Panel bot)
        {
            // ── 難度按鈕列 ─────────────────────────────────────────
            // 文字改為「電腦難度：」（不出現 AI 字樣）
            const int dBtnW = 100, dBtnH = 30, dGap = 5;
            Label lblDiff = new Label();
            lblDiff.Text      = "電腦難度：";
            lblDiff.Font      = new Font("Microsoft JhengHei", 9f, FontStyle.Bold);
            lblDiff.ForeColor = Color.FromArgb(170, 170, 185);
            lblDiff.Size      = new Size(76, dBtnH);
            lblDiff.TextAlign = ContentAlignment.MiddleRight;
            lblDiff.AutoSize  = false;

            int diffTotalW = lblDiff.Width + 8 + 4 * dBtnW + 3 * dGap;
            int diffStartX = (FormW - diffTotalW) / 2;
            lblDiff.Location = new Point(diffStartX, 15);
            bot.Controls.Add(lblDiff);

            for (int i = 0; i < 4; i++)
            {
                Button b = new Button();
                b.Text      = DiffLabels[i];
                b.Font      = new Font("Microsoft JhengHei", 9f, FontStyle.Bold);
                b.ForeColor = Color.White;
                b.FlatStyle = FlatStyle.Flat;
                b.Location  = new Point(diffStartX + lblDiff.Width + 8 + i * (dBtnW + dGap), 15);
                b.Size      = new Size(dBtnW, dBtnH);
                b.Cursor    = Cursors.Hand;
                b.FlatAppearance.BorderSize = 1;
                b.Tag    = i;
                b.Click += DiffBtn_Click;
                bot.Controls.Add(b);
                _diffBtns[i] = b;
            }
            UpdateDiffBtns();

            // ── 操作按鈕列（移除會出現方框的 emoji）─────────────────
            const int aBtnW = 178, aBtnH = 36, aGap = 12;
            int actStartX = (FormW - 3 * aBtnW - 2 * aGap) / 2;
            const int aBtnY = 60;

            // 使用 BMP Unicode 箭頭，不用 emoji（避免方框問題）
            Button btnNew = MakeActBtn(bot, "↺  新遊戲  (N)",
                Color.FromArgb(22, 128, 52), actStartX, aBtnY, aBtnW, aBtnH);
            btnNew.Click += (s, e) => NewGame();

            Button btnUndo = MakeActBtn(bot, "↩  悔棋      (U)",
                Color.FromArgb(128, 88, 18), actStartX + aBtnW + aGap, aBtnY, aBtnW, aBtnH);
            btnUndo.Click += (s, e) => UndoMove();

            Button btnMode = MakeActBtn(bot, "⇄  切換對戰模式",
                Color.FromArgb(64, 64, 155), actStartX + 2 * (aBtnW + aGap), aBtnY, aBtnW, aBtnH);
            btnMode.Click += (s, e) => ToggleMode();

            // ── 音樂開關（右上角小按鈕）─────────────────────────────
            _btnMusic = new Button();
            _btnMusic.Text      = "♫ 音樂 ON";
            _btnMusic.Font      = new Font("Microsoft JhengHei", 8f, FontStyle.Bold);
            _btnMusic.ForeColor = Color.White;
            _btnMusic.BackColor = Color.FromArgb(80, 60, 100);
            _btnMusic.FlatStyle = FlatStyle.Flat;
            _btnMusic.Location  = new Point(FormW - 80, 5);
            _btnMusic.Size      = new Size(72, 24);
            _btnMusic.Cursor    = Cursors.Hand;
            _btnMusic.FlatAppearance.BorderSize         = 0;
            _btnMusic.FlatAppearance.MouseOverBackColor = Color.FromArgb(110, 80, 135);
            _btnMusic.Click += (s, e) =>
            {
                MusicPlayer.Toggle();
                _btnMusic.Text      = MusicPlayer.IsPlaying ? "♫ 音樂 ON" : "♩ 音樂 OFF";
                _btnMusic.BackColor = MusicPlayer.IsPlaying
                    ? Color.FromArgb(80, 60, 100) : Color.FromArgb(55, 55, 65);
            };
            bot.Controls.Add(_btnMusic);
        }

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // 關閉確認
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        protected override void OnFormClosing(FormClosingEventArgs e)
        {
            base.OnFormClosing(e);
            if (e.CloseReason == CloseReason.UserClosing)
            {
                DialogResult res = MessageBox.Show(
                    "確定要關閉遊戲嗎？",
                    "關閉遊戲",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question,
                    MessageBoxDefaultButton.Button2);

                if (res == DialogResult.No)
                    e.Cancel = true;
                else
                    MusicPlayer.Stop();  // 關閉前停止音樂
            }
        }

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // Helper 工廠
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        private static Panel MakeCard(Control parent, int x, int y, int w, int h, Color bg)
        {
            Panel p = new Panel();
            p.Location  = new Point(x, y);
            p.Size      = new Size(w, h);
            p.BackColor = bg;
            parent.Controls.Add(p);
            return p;
        }

        private static Label MakeLbl(Control parent, string text, Font font, Color color,
                                     Point loc, Size sz)
        {
            Label l = new Label();
            l.Text      = text;
            l.Font      = font;
            l.ForeColor = color;
            l.Location  = loc;
            l.Size      = sz;
            l.TextAlign = ContentAlignment.MiddleCenter;
            l.AutoSize  = false;
            parent.Controls.Add(l);
            return l;
        }

        private static Button MakeActBtn(Control parent, string text, Color color,
                                         int x, int y, int w, int h)
        {
            Button b = new Button();
            b.Text      = text;
            b.Font      = new Font("Microsoft JhengHei", 9.5f, FontStyle.Bold);
            b.ForeColor = Color.White;
            b.BackColor = color;
            b.FlatStyle = FlatStyle.Flat;
            b.Location  = new Point(x, y);
            b.Size      = new Size(w, h);
            b.Cursor    = Cursors.Hand;
            b.FlatAppearance.BorderSize         = 0;
            b.FlatAppearance.MouseOverBackColor = Lighten(color, 25);
            parent.Controls.Add(b);
            return b;
        }

        private void DiffBtn_Click(object sender, EventArgs e)
        {
            int idx = (int)((Button)sender).Tag;
            _ai.Difficulty = (Difficulty)idx;
            UpdateDiffBtns();
        }

        private void UpdateDiffBtns()
        {
            int sel = (int)_ai.Difficulty;
            for (int i = 0; i < 4; i++)
            {
                if (_diffBtns[i] == null) continue;
                bool on = (i == sel);
                _diffBtns[i].BackColor = on ? DiffColors[i] : Color.FromArgb(46, 46, 60);
                _diffBtns[i].ForeColor = on ? Color.White   : Color.FromArgb(160, 160, 180);
                _diffBtns[i].FlatAppearance.BorderColor =
                    on ? Lighten(DiffColors[i], 30) : Color.FromArgb(68, 68, 85);
            }
        }

        private static Color Lighten(Color c, int d)
        {
            return Color.FromArgb(
                Math.Min(255, c.R + d),
                Math.Min(255, c.G + d),
                Math.Min(255, c.B + d));
        }

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // 棋盤繪圖
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        private void Board_Paint(object sender, PaintEventArgs e)
        {
            Graphics g = e.Graphics;
            g.SmoothingMode     = SmoothingMode.AntiAlias;
            g.InterpolationMode = InterpolationMode.HighQualityBicubic;
            g.TextRenderingHint = TextRenderingHint.ClearTypeGridFit;

            DrawBackground(g);
            DrawGrid(g);
            DrawStarPoints(g);
            DrawCoordinates(g);
            DrawPieces(g);

            if (_hover.HasValue && !_game.IsGameOver && !_aiThinking)
                DrawHover(g, _hover.Value);

            if (_game.IsGameOver && _game.WinningCells != null)
                DrawWinLine(g);
        }

        private static void DrawBackground(Graphics g)
        {
            Rectangle rect = new Rectangle(0, 0, BoardSz, BoardSz);
            using (LinearGradientBrush bg = new LinearGradientBrush(rect,
                Color.FromArgb(216, 145, 62), Color.FromArgb(174, 108, 34), 40f))
                g.FillRectangle(bg, rect);

            Random rng = new Random(7);
            using (Pen grain = new Pen(Color.FromArgb(16, 0, 0, 0), 1.2f))
                for (int i = 0; i < 28; i++)
                {
                    int y0 = rng.Next(0, BoardSz), y1 = y0 + rng.Next(-18, 18);
                    g.DrawLine(grain, 0, y0, BoardSz, y1);
                }

            using (Pen border = new Pen(Color.FromArgb(116, 74, 18), 3))
                g.DrawRectangle(border, 2, 2, BoardSz - 5, BoardSz - 5);
        }

        private static void DrawGrid(Graphics g)
        {
            using (Pen pen = new Pen(Color.FromArgb(88, 52, 12), 1f))
                for (int i = 0; i < GomokuGame.BoardSize; i++)
                {
                    g.DrawLine(pen, Pad + i * Cell, Pad, Pad + i * Cell, Pad + Grid);
                    g.DrawLine(pen, Pad, Pad + i * Cell, Pad + Grid, Pad + i * Cell);
                }
        }

        private static void DrawStarPoints(Graphics g)
        {
            int[] pts = { 3, 7, 11 };
            using (SolidBrush b = new SolidBrush(Color.FromArgb(88, 52, 12)))
                foreach (int r in pts)
                    foreach (int c in pts)
                        g.FillEllipse(b, Pad + c * Cell - 4, Pad + r * Cell - 4, 8, 8);
        }

        private static void DrawCoordinates(Graphics g)
        {
            const string cols = "ABCDEFGHJKLMNOP";
            using (Font font  = new Font("Consolas", 8f))
            using (SolidBrush brush = new SolidBrush(Color.FromArgb(98, 60, 18)))
                for (int i = 0; i < GomokuGame.BoardSize; i++)
                {
                    int px = Pad + i * Cell, py = Pad + i * Cell;
                    SizeF cs = g.MeasureString(cols[i].ToString(), font);
                    g.DrawString(cols[i].ToString(), font, brush, px - cs.Width / 2, Pad / 2 - cs.Height / 2);
                    g.DrawString(cols[i].ToString(), font, brush, px - cs.Width / 2, BoardSz - Pad / 2 - cs.Height / 2);
                    string row = (GomokuGame.BoardSize - i).ToString();
                    SizeF rs = g.MeasureString(row, font);
                    g.DrawString(row, font, brush, Pad / 2 - rs.Width / 2, py - rs.Height / 2);
                    g.DrawString(row, font, brush, BoardSz - Pad / 2 - rs.Width / 2, py - rs.Height / 2);
                }
        }

        private void DrawPieces(Graphics g)
        {
            int[] last = _game.LastMove;
            for (int r = 0; r < GomokuGame.BoardSize; r++)
                for (int c = 0; c < GomokuGame.BoardSize; c++)
                {
                    Player pl = _game.Board[r, c];
                    if (pl == Player.None) continue;
                    bool isLast = last != null && last[0] == r && last[1] == c;
                    DrawPiece(g, Pad + c * Cell, Pad + r * Cell, pl, isLast);
                }
        }

        private static void DrawPiece(Graphics g, int cx, int cy, Player player, bool isLast)
        {
            int R = Radius;
            Rectangle rc = new Rectangle(cx - R, cy - R, R * 2, R * 2);

            using (SolidBrush shadow = new SolidBrush(Color.FromArgb(55, 0, 0, 0)))
                g.FillEllipse(shadow, cx - R + 2, cy - R + 3, R * 2, R * 2);

            if (player == Player.Black)
            {
                using (LinearGradientBrush fill = new LinearGradientBrush(rc,
                    Color.FromArgb(90, 90, 90), Color.FromArgb(4, 4, 4),
                    LinearGradientMode.ForwardDiagonal))
                    g.FillEllipse(fill, rc);
            }
            else
            {
                using (LinearGradientBrush fill = new LinearGradientBrush(rc,
                    Color.FromArgb(255, 255, 255), Color.FromArgb(198, 198, 198),
                    LinearGradientMode.ForwardDiagonal))
                    g.FillEllipse(fill, rc);
                using (Pen border = new Pen(Color.FromArgb(155, 155, 155), 1.2f))
                    g.DrawEllipse(border, rc);
            }

            int sh = R - 4;
            if (sh > 0)
            {
                Rectangle shrc = new Rectangle(cx - R + 4, cy - R + 4, sh, sh);
                int alpha = player == Player.Black ? 60 : 95;
                using (LinearGradientBrush shine = new LinearGradientBrush(shrc,
                    Color.FromArgb(alpha, 255, 255, 255),
                    Color.FromArgb(0, 255, 255, 255),
                    LinearGradientMode.ForwardDiagonal))
                    g.FillEllipse(shine, shrc);
            }

            if (isLast)
                using (SolidBrush mark = new SolidBrush(Color.FromArgb(230, 50, 50)))
                    g.FillEllipse(mark, cx - 4, cy - 4, 8, 8);
        }

        /// <summary>在頂部卡片 Paint 事件中繪製小棋子（直接在卡片 GDI 上畫，無透明背景問題）</summary>
        private static void DrawPieceSmall(Graphics g, int cx, int cy, Player player, int r)
        {
            Rectangle rc = new Rectangle(cx - r, cy - r, r * 2, r * 2);

            using (SolidBrush shadow = new SolidBrush(Color.FromArgb(50, 0, 0, 0)))
                g.FillEllipse(shadow, cx - r + 1, cy - r + 2, r * 2, r * 2);

            if (player == Player.Black)
            {
                using (LinearGradientBrush fill = new LinearGradientBrush(rc,
                    Color.FromArgb(85, 85, 85), Color.FromArgb(8, 8, 8),
                    LinearGradientMode.ForwardDiagonal))
                    g.FillEllipse(fill, rc);
            }
            else
            {
                using (LinearGradientBrush fill = new LinearGradientBrush(rc,
                    Color.White, Color.FromArgb(200, 200, 200),
                    LinearGradientMode.ForwardDiagonal))
                    g.FillEllipse(fill, rc);
                using (Pen border = new Pen(Color.FromArgb(155, 155, 155), 1f))
                    g.DrawEllipse(border, rc);
            }

            int sh = r - 3;
            if (sh > 0)
            {
                Rectangle shrc = new Rectangle(cx - r + 3, cy - r + 3, sh, sh);
                int alpha = player == Player.Black ? 55 : 90;
                using (LinearGradientBrush shine = new LinearGradientBrush(shrc,
                    Color.FromArgb(alpha, 255, 255, 255),
                    Color.FromArgb(0, 255, 255, 255),
                    LinearGradientMode.ForwardDiagonal))
                    g.FillEllipse(shine, shrc);
            }
        }

        private void DrawHover(Graphics g, Point cell)
        {
            if (_game.Board[cell.Y, cell.X] != Player.None) return;
            int cx = Pad + cell.X * Cell, cy = Pad + cell.Y * Cell;
            Color hc = _game.CurrentPlayer == Player.Black
                ? Color.FromArgb(95, 15, 15, 15) : Color.FromArgb(95, 240, 240, 240);
            using (SolidBrush b = new SolidBrush(hc))
                g.FillEllipse(b, cx - Radius, cy - Radius, Radius * 2, Radius * 2);
        }

        private void DrawWinLine(Graphics g)
        {
            List<int[]> cells = _game.WinningCells;
            if (cells == null || cells.Count < 2) return;

            cells.Sort((a, b) => a[1] != b[1] ? a[1].CompareTo(b[1]) : a[0].CompareTo(b[0]));
            double x1 = Pad + cells[0][1] * Cell,               y1 = Pad + cells[0][0] * Cell;
            double x2 = Pad + cells[cells.Count - 1][1] * Cell, y2 = Pad + cells[cells.Count - 1][0] * Cell;

            double dx = x2 - x1, dy = y2 - y1;
            double len = Math.Sqrt(dx * dx + dy * dy);
            if (len > 0)
            { const int ext = 14; x1 -= dx / len * ext; y1 -= dy / len * ext; x2 += dx / len * ext; y2 += dy / len * ext; }

            using (Pen pen = new Pen(Color.FromArgb(215, 255, 55, 55), 4.5f))
            { pen.StartCap = LineCap.Round; pen.EndCap = LineCap.Round; g.DrawLine(pen, (float)x1, (float)y1, (float)x2, (float)y2); }
        }

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // 輸入
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        private void Board_MouseMove(object sender, MouseEventArgs e)
        {
            Point? c = ToCell(e.Location);
            if (!Equals(c, _hover)) { _hover = c; _board.Invalidate(); }
        }

        private async void Board_MouseClick(object sender, MouseEventArgs e)
        {
            if (_game.IsGameOver || _aiThinking) return;
            if (_aiMode && _game.CurrentPlayer == Player.White) return;

            Point? cell = ToCell(e.Location);
            if (!cell.HasValue) return;
            if (!_game.PlacePiece(cell.Value.Y, cell.Value.X)) return;

            if (!_started) { _started = true; _clock.Start(); }
            SoundManager.PlayBlack();
            RefreshBoard();

            if (_game.IsGameOver) { GameOver(); return; }
            if (_aiMode) await AIMoveAsync();
        }

        protected override void OnKeyDown(KeyEventArgs e)
        {
            base.OnKeyDown(e);
            if (e.KeyCode == Keys.N) NewGame();
            if (e.KeyCode == Keys.U) UndoMove();
        }

        private static Point? ToCell(Point p)
        {
            int c = (int)Math.Round((p.X - Pad) / (double)Cell);
            int r = (int)Math.Round((p.Y - Pad) / (double)Cell);
            if (c < 0 || c >= GomokuGame.BoardSize || r < 0 || r >= GomokuGame.BoardSize) return null;
            return new Point(c, r);
        }

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // 遊戲邏輯
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        private async Task AIMoveAsync()
        {
            int ver = _gameVersion;
            _aiThinking = true;
            RefreshStatus();

            int thinkMs;
            switch (_ai.Difficulty)
            {
                case Difficulty.Easy:   thinkMs = 200; break;
                case Difficulty.Hard:   thinkMs = 400; break;
                case Difficulty.Master: thinkMs = 100; break;
                default:                thinkMs = 300; break;
            }
            await Task.Delay(thinkMs);

            if (_gameVersion != ver || _game.IsGameOver)
            { _aiThinking = false; RefreshStatus(); return; }

            int[] move = await Task.Run(() => _ai.GetBestMove(_game, Player.White));

            if (_gameVersion != ver || _game.IsGameOver)
            { _aiThinking = false; RefreshStatus(); return; }

            _game.PlacePiece(move[0], move[1]);
            SoundManager.PlayWhite();
            _aiThinking = false;
            RefreshBoard();
            if (_game.IsGameOver) GameOver();
        }

        private void NewGame()
        {
            _gameVersion++;
            _aiThinking = false;
            _game.Reset();
            _elapsed = 0;
            _started = false;
            _clock.Stop();
            RefreshTimer();
            RefreshBoard();
            RefreshStatus();
            SoundManager.PlayNewGame();
        }

        private void UndoMove()
        {
            if (_aiThinking || _game.MoveCount == 0) return;
            int undoCount = _aiMode ? Math.Min(2, _game.MoveCount) : 1;
            _game.Undo(undoCount);
            RefreshBoard();
            RefreshStatus();
            SoundManager.PlayUndo();
        }

        private void ToggleMode()
        {
            _aiMode        = !_aiMode;
            _lblWName.Text = _aiMode ? "電腦" : "玩家 2";
            NewGame();
        }

        private void GameOver()
        {
            _clock.Stop();
            _board.Invalidate();
            RefreshStatus();
            SoundManager.PlayWin();

            string msg;
            if (_game.Winner == Player.None)         msg = "棋盤已滿，平局！";
            else if (_game.Winner == Player.Black)   msg = _aiMode ? "🎉 恭喜您獲勝！" : "⚫ 黑棋獲勝！";
            else                                     msg = _aiMode ? "電腦獲勝！再接再厲！" : "⚪ 白棋獲勝！";

            string time = string.Format("{0:D2}:{1:D2}", _elapsed / 60, _elapsed % 60);
            DialogResult ans = MessageBox.Show(
                msg + "\n\n遊戲時間：" + time + "　共 " + _game.MoveCount + " 手\n\n要再玩一局嗎？",
                "遊戲結束", MessageBoxButtons.YesNo, MessageBoxIcon.Information);

            if (ans == DialogResult.Yes) NewGame();
        }

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // UI 更新
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        private void RefreshBoard()
        {
            _board.Invalidate();
            RefreshStatus();
        }

        private void RefreshStatus()
        {
            Color activeCard   = Color.FromArgb(36, 68, 110);   // 藍色高亮
            Color inactiveCard = Color.FromArgb(44, 44, 58);    // 暗色待機

            if (_game.IsGameOver)
            {
                _leftCard.BackColor  = inactiveCard;
                _rightCard.BackColor = inactiveCard;

                if (_game.Winner == Player.None)
                { _lblStatus.Text = "平局！"; _lblStatus.ForeColor = Color.FromArgb(220, 200, 80); }
                else if (_game.Winner == Player.Black)
                { _lblStatus.Text = "黑棋獲勝！"; _lblStatus.ForeColor = Color.FromArgb(100, 220, 100); }
                else
                { _lblStatus.Text = "白棋獲勝！"; _lblStatus.ForeColor = Color.FromArgb(100, 220, 100); }
            }
            else if (_aiThinking)
            {
                _leftCard.BackColor  = inactiveCard;
                _rightCard.BackColor = activeCard;
                _lblStatus.Text      = "電腦思考中…";
                _lblStatus.ForeColor = Color.FromArgb(255, 180, 60);
            }
            else
            {
                bool blackTurn = (_game.CurrentPlayer == Player.Black);
                _leftCard.BackColor  = blackTurn ? activeCard : inactiveCard;
                _rightCard.BackColor = blackTurn ? inactiveCard : activeCard;
                _lblStatus.Text      = blackTurn ? "您的回合" : "電腦回合";
                _lblStatus.ForeColor = Color.FromArgb(120, 200, 120);
            }

            // 卡片背景變化後需重繪（Paint 事件會重新畫棋子在新背景上）
            _leftCard.Invalidate();
            _rightCard.Invalidate();
        }

        private void RefreshTimer()
        {
            _lblTimer.Text = string.Format("{0:D2}:{1:D2}", _elapsed / 60, _elapsed % 60);
        }
    }

    // ── 雙緩衝面板 ──────────────────────────────────────────────────
    public sealed class DoubleBufferedPanel : Panel
    {
        public DoubleBufferedPanel()
        {
            DoubleBuffered = true;
            SetStyle(
                ControlStyles.AllPaintingInWmPaint |
                ControlStyles.UserPaint |
                ControlStyles.OptimizedDoubleBuffer, true);
        }
    }
}
